on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  goreadme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Generate report card
      uses: creekorful/goreportcard-action@v1.0
    - name: Go Test
      uses: cedrickring/golang-action@1.5.2
    - name: Update readme according to Go doc
      uses: posener/goreadme@v1
      with:
        badge-codecov: 'true'
        badge-godoc: 'true'
        badge-goreportcard: 'true'
        # Optional: Token allows goreadme to comment the PR with diff preview.
        github-token: '${{ secrets.GITHUB_TOKEN }}'